name: CI
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
permissions: { contents: read }
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  node:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '22', cache: 'npm' }
      - run: npm ci --no-audit --fund=false
      - run: npx prettier -c .
      - run: npx eslint . --max-warnings=0
      - run: npm test --silent
      - run: npm pack --dry-run
  python:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12', cache: 'pip' }
      - run: python -m pip install --upgrade pip
      - run: pip install poetry
      - run: poetry install --no-interaction
      - run: poetry run ruff check .
      - run: poetry run black --check .
      - run: PYTHONPATH=src poetry run pytest -q
